# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.IntegerField(default=100, verbose_name='шанс')),
                ('template_path', models.CharField(default='master', max_length=10, verbose_name='папка с шаблонами')),
                ('is_secure', models.BooleanField(default=False, verbose_name='https')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='sites.Site', verbose_name='сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('short_url', models.URLField(verbose_name='ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='номер телефона')),
                ('message', models.TextField(verbose_name='текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Area', verbose_name='площадка')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Campaign', verbose_name='компания')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Visitor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Partner', verbose_name='партнёр'),
        ),
    ]
