# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='code',
            field=models.CharField(default='MLqTqKGjlD', max_length=10),
        ),
    ]
