# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20161217_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='see_available',
            field=models.BooleanField(default=False, verbose_name='доступен для обработки'),
        ),
    ]
