# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_order_see_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='chanel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='номер канала'),
        ),
    ]
