# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_manager_chanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='имя модератора')),
                ('code', models.CharField(default=index.models.unique_code, max_length=10, verbose_name='код')),
                ('chanel', models.CharField(blank=True, max_length=30, null=True, verbose_name='номер канала')),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_moderator',
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=50, verbose_name='имя менеджера'),
        ),
    ]
